In [25]:
import tensorflow as tf
sess = tf.InteractiveSession()
a = tf.constant(1.0,shape = [2,2])
tf.global_variables_initializer().run()
a.eval()

array([[ 1.,  1.]], dtype=float32)

In [26]:
import tensorflow as tf
sess = tf.InteractiveSession()
var = tf.Variable(tf.truncated_normal([5,5],stddev=0.5))
print('var:')

t1 = tf.constant(2.0,shape = [1,2])

tf.global_variables_initializer().run()
print(var.eval())

weight = tf.nn.l2_loss(var)
print(weight.eval())

print(t1.eval())
print(tf.nn.l2_loss(t1).eval())


var:
[[ 0.48688594  0.12387454 -0.28428075 -0.15835166  0.51630539]
 [ 0.26394051  0.63391739  0.28149346 -0.15570714  0.2803525 ]
 [ 0.33287415  0.10751921  0.0802837   0.31196964  0.06149322]
 [ 0.05600385 -0.39538905  0.01656845  0.37422109  0.2319731 ]
 [-0.0335922   0.67162383  0.54189664 -0.12770496 -0.69404393]]
1.55292
[[ 2.  2.]]
4.0


In [1]:
import tensorflow as tf
sess = tf.InteractiveSession()
a = tf.constant(1.2,shape = [1])
b = tf.constant(2.3,shape = [1])
tf.add_to_collection('co1',a)
tf.add_to_collection('col',b)
c = tf.get_collection('col')
print(c)
print(c[0])

[<tf.Tensor 'Const_1:0' shape=(1,) dtype=float32>]
Tensor("Const_1:0", shape=(1,), dtype=float32)


In [1]:
import tensorflow as tf
import numpy as np

""" tf.add_to_collection：把变量放入一个集合，把很多变量变成一个列表
    tf.get_collection：从一个结合中取出全部变量，是一个列表
    tf.add_n：把一个列表的东西都依次加起来 """

a = tf.constant(4)
b = tf.constant(4)

tf.add_to_collection('loss', a)
tf.add_to_collection('loss', b)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print()
    print(tf.get_collection('loss'))
    print()
    print( sess.run(tf.add_n(tf.get_collection('loss'))))


[<tf.Tensor 'Const:0' shape=() dtype=int32>, <tf.Tensor 'Const_1:0' shape=() dtype=int32>]

8


In [4]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import tensorflow as tf 

a = tf.constant([[1.0, 2.0],[1.0, 2.0],[1.0, 2.0]]) 
b = tf.constant([2.0,1.0])  
c = tf.constant([1.0])
sess = tf.Session()
print('bias_add:')
print(sess.run(tf.nn.bias_add(a, b)))
# 因为 a 最后一维的维度是 2 ，但是 c 的维度是 1，所以以下语句将发生错误
#print(sess.run(tf.nn.bias_add(a, c)))
# 但是 tf.add() 可以正确运行
print('add:')
print(sess.run(tf.add(a, c)))

bias_add:
[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]
add:
[[ 2.  3.]
 [ 2.  3.]
 [ 2.  3.]]


In [10]:
import tensorflow as tf
sess = tf.InteractiveSession()
a = tf.constant(2.0,shape=[2,2])
print(a.eval())
b = a**2
print(b.eval())

print()
print(b.get_shape())
print(b.get_shape()[0].value)

[[ 2.  2.]
 [ 2.  2.]]
[[ 4.  4.]
 [ 4.  4.]]

(2, 2)
2


In [23]:
import tensorflow as tf
sess = tf.InteractiveSession()
a = tf.constant([[1,2,3,4,5,6,7,8],[8,7,6,5,4,3,2,1]],tf.float32)
b = tf.constant([2,3])
print(a.eval())
c = tf.nn.in_top_k(predictions = a,targets = b,k = 4)
print(c.eval())

[[ 1.  2.  3.  4.  5.  6.  7.  8.]
 [ 8.  7.  6.  5.  4.  3.  2.  1.]]
[False  True]


In [8]:
#-*- coding:utf-8 -*-
import tensorflow as tf

#创建的图:一个先入先出队列,以及初始化,出队,+1,入队操作
q = tf.FIFOQueue(3, "float")
init = q.enqueue_many(([0.1, 0.2, 0.3],))
x = q.dequeue()
y = x + 1
q_inc = q.enqueue([y])

#开启一个session,session是会话,会话的潜在含义是状态保持,各种tensor的状态保持
with tf.Session() as sess:
        sess.run(init)

        for i in range(2):
                sess.run(q_inc)

        quelen =  sess.run(q.size())
        print (quelen)
        
        #打印队列里的数据
        for i in range(quelen):
                print (sess.run(q.dequeue()))

3
0.3
1.1
1.2


In [1]:
#-*- coding:utf-8 -*-
import tensorflow as tf
import sys
#创建稍微复杂一点的队列作为例子
q = tf.FIFOQueue(1000,"float")
#计数器
counter = tf.Variable(0.0)
#操作:给计数器加一
increment_op = tf.assign_add(counter,tf.constant(1.0))
#操作:将计数器加入队列
enqueue_op = q.enqueue(counter)

#创建一个队列管理器QueueRunner，用这两个操作向q中添加元素。目前我们只使用一个线程:
qr = tf.train.QueueRunner(q,enqueue_ops=[increment_op,enqueue_op]*1)


#从队列管理器中创建线程，并启动:
#主线程
with tf.Session() as sess:
        sess.run(tf.initialize_all_variables())
        enqueue_threads = qr.create_threads(sess, start=True)  # 启动入队线程
        #主线程
        for i in range(10):
                print("----------------------:")
                print((sess.run(q.dequeue())))


Instructions for updating:
Use `tf.global_variables_initializer` instead.
----------------------:
2.0
----------------------:
4.0
----------------------:
7.0
----------------------:
13.0
----------------------:
15.0
----------------------:
23.0
----------------------:
32.0
----------------------:
38.0
----------------------:
42.0
----------------------:
46.0
ERROR:tensorflow:Exception in QueueRunner: Attempted to use a closed Session.
ERROR:tensorflow:Exception in QueueRunner: Attempted to use a closed Session.


Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\hndnkj\Anaconda3\envs\tensorflow\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\hndnkj\Anaconda3\envs\tensorflow\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\hndnkj\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\queue_runner_impl.py", line 234, in _run
    sess.run(enqueue_op)
  File "C:\Users\hndnkj\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 778, in run
    run_metadata_ptr)
  File "C:\Users\hndnkj\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 914, in _run
    raise RuntimeError('Attempted to use a closed Session.')
RuntimeError: Attempted to use a closed Session.
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Users\hndnkj\Anaconda3\envs\tensorflow\lib\threading.py", line 914, in _b

In [14]:
#-*- coding:utf-8 -*-
import tensorflow as tf
import sys
#创建稍微复杂一点的队列作为例子
q = tf.FIFOQueue(1000,"float")
#计数器
counter = tf.Variable(0.0)
#操作:给计数器加一
increment_op = tf.assign_add(counter,tf.constant(1.0))
#操作:将计数器加入队列
enqueue_op = q.enqueue(counter)

#创建一个队列管理器QueueRunner，用这两个操作向q中添加元素。目前我们只使用一个线程:
qr = tf.train.QueueRunner(q,enqueue_ops=[[increment_op,enqueue_op]]*1)

# 主线程
sess = tf.Session()
sess.run(tf.global_variables_initializer())

enqueue_threads = qr.create_threads(sess, start=True)  # 启动入队线程

# 主线程
for i in range(0, 10):
    print(sess.run(q.dequeue()))


1.0
2.0
4.0
22.0
22.0
23.0
29.0
31.0
33.0
48.0


In [ ]:
#-*- coding:utf-8 -*-
import tensorflow as tf
import sys
#创建稍微复杂一点的队列作为例子
q = tf.FIFOQueue(1000,"float")
#计数器
counter = tf.Variable(0.0)
#操作:给计数器加一
increment_op = tf.assign_add(counter,tf.constant(1.0))
#操作:将计数器加入队列
enqueue_op = q.enqueue(counter)

#创建一个队列管理器QueueRunner，用这两个操作向q中添加元素。目前我们只使用一个线程:
qr = tf.train.QueueRunner(q,enqueue_ops=[increment_op,enqueue_op]*1)

# 主线程
sess = tf.Session()
sess.run(tf.initialize_all_variables())

#enqueue_threads = qr.create_threads(sess, start=True)  # 启动入队线程

# 主线程
for i in range(0, 10):
    print("-------------------------")
    print(sess.run(q.dequeue()))


Instructions for updating:
Use `tf.global_variables_initializer` instead.
-------------------------


In [12]:
#-*- coding:utf-8 -*-
import tensorflow as tf
import sys
#创建稍微复杂一点的队列作为例子
q = tf.FIFOQueue(1000,"float")
#计数器
counter = tf.Variable(0.0)
#操作:给计数器加一
increment_op = tf.assign_add(counter,tf.constant(1.0))
enqueue_op = q.enqueue(counter) # 操作：计数器值加入队列
#操作:将计数器加入队列
qr = tf.train.QueueRunner(q, enqueue_ops=[increment_op, enqueue_op] * 1)

# 主线程
sess = tf.Session()
sess.run(tf.global_variables_initializer())

#Coordinator:协调器,协调线程间的关系,可以视为一种信号量,用来做同步
coord = tf.train.Coordinator()

## 启动入队线程, Coordinator是线程的参数
enqueue_threads = qr.create_threads(sess, coord = coord,start=True)  # 启动入队线程

# 主线程
for i in range(0, 10):
    print("-------------------------")
    print(sess.run(q.dequeue()))

#通知其他线程关闭
coord.request_stop()
#其他所有线程关闭之后，这一函数才能返回
#join操作经常用在线程当中,其作用是等待某线程结束
coord.join(enqueue_threads)

-------------------------
6.0
-------------------------
7.0
-------------------------
8.0
-------------------------
9.0
-------------------------
10.0
-------------------------
12.0
-------------------------
23.0
-------------------------
28.0
-------------------------
28.0
-------------------------
34.0
