In [1]:
import tensorflow as tf
sess = tf.InteractiveSession()

print('----------activation----------------')
a = tf.truncated_normal([2,3],stddev=0.1)
print(a.eval())
#b = tf.nn.relu(-1)
b = tf.nn.sigmoid(0.0)
print(b.eval())

print('-----------dropout---------------')
x1 = tf.ones([2,5])
print(x1.eval())
print(tf.reduce_sum(x1).eval())
x2 = tf.nn.dropout(x1,0.1)
print(x2.eval())
x3 = tf.nn.dropout(x3,0.9)
print(x3.eval())

----------activation----------------
[[ 0.03171368 -0.04691516 -0.00922689]
 [-0.13322793  0.10589593  0.09498637]]
0.5
-----------dropout---------------
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
10.0
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


NameError: name 'x3' is not defined

In [4]:
4/3

1.3333333333333333

In [2]:
[[ 1.25  1.25  1.25]
 [ 1.25  1.25  1.25]]

[[ 0.    1.25  1.25]
 [ 1.25  1.25  1.25]]

SyntaxError: invalid syntax (<ipython-input-2-524877a26995>, line 1)