In [36]:
import tensorflow as tf
import numpy as np

y = np.array([[1.,1.,1.,1.],[1.,1.,1.,1.],[1.,1.,1.,1.],[1.,1.,1.,1.]])
sess = tf.Session()
print(sess.run(tf.reduce_sum(y,-1)))
z = tf.nn.softmax(y)

print(z)
print(type(z))
sess = tf.Session()
sess.run(z)

[ 4.  4.  4.  4.]
Tensor("Softmax_8:0", shape=(4, 4), dtype=float64)
<class 'tensorflow.python.framework.ops.Tensor'>


array([[ 0.25,  0.25,  0.25,  0.25],
       [ 0.25,  0.25,  0.25,  0.25],
       [ 0.25,  0.25,  0.25,  0.25],
       [ 0.25,  0.25,  0.25,  0.25]])

In [37]:
x = np.array([[1.,1.,1.,1.],[1.,1.,1.,1.],[1.,1.,1.,1.],[1.,1.,1.,1.]])
m = tf.exp(x)
softmax = tf.exp(x)/tf.reduce_sum(tf.exp(x),-1)
print((tf.reduce_sum(tf.exp(x),-1)).shape)
sess = tf.Session()
sess.run(softmax)

(4,)


array([[ 0.25,  0.25,  0.25,  0.25],
       [ 0.25,  0.25,  0.25,  0.25],
       [ 0.25,  0.25,  0.25,  0.25],
       [ 0.25,  0.25,  0.25,  0.25]])

In [31]:
a = tf.constant(2)
print(type(a))
print(a)
sess = tf.Session()
sess.run(a)

<class 'tensorflow.python.framework.ops.Tensor'>
Tensor("Const_8:0", shape=(), dtype=int32)


2

In [39]:
x = np.array([[1.,1.,1.,1.],[1.,2.,1.,1.],[1.,1.,1.,1.],[1.,1.,1.,1.]])
div = np.array([1,2,3,4])
x/div

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 1.        ,  1.        ,  0.33333333,  0.25      ],
       [ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 1.        ,  0.5       ,  0.33333333,  0.25      ]])

In [1]:
import tensorflow as tf
sess = tf.InteractiveSession()
a = tf.constant(10)
b = tf.constant(3)
c = tf.subtract(a,b)
d = tf.pow(c,2)
x = tf.random_normal([2,2],mean=0.0,stddev=1.0)
print(c.eval())
print(d.eval())
print(x.eval())

7
49
[[ 0.  0.]
 [ 0.  0.]]


In [18]:
import tensorflow as tf
a = tf.constant(5)
b = tf.multiply(a,5)
sess = tf.Session()
print(sess.run(b,feed_dict={a:100}))

500


In [2]:
import tensorflow as tf
import numpy as np
sess = tf.InteractiveSession()
a = tf.placeholder(tf.int32,shape=[2,2],name='placeholder_a')
b = tf.placeholder(tf.int32,shape=[2,2],name='placeholder_b')
c = tf.matmul(a,b)
print(c.eval({a:np.ones([2,2]),b:np.ones([2,2])}))

v1 = tf.Variable(3)
v2 = v1.assign(100)
w = tf.pow(v2,2)
init = tf.global_variables_initializer()
init.run()
print(w.eval())

[[2 2]
 [2 2]]
10000


In [29]:
import tensorflow as tf
import numpy as np
sess = tf.InteractiveSession()
a = np.array([2,2,3,3,4,4],np.float32)
a = tf.reduce_mean(a)
#a = tf.log(a)
print(a.eval())
print('----------------------')

m = np.array([1,0,5,0,0],np.int32)
n = np.array([1,1,0,5,0],np.int32)
temp = tf.argmax(m,0)
print(temp.eval())
print(tf.argmax(n,0).eval())
match = tf.equal(m,n)
print(match.eval())
print(tf.cast(match,tf.float32).eval())

3.0
----------------------
2
3
[ True False False False  True]
[ 1.  0.  0.  0.  1.]
