In [1]:
import tensorflow as tf
import numpy as np

In [3]:
a = np.arange(16).reshape([2,2,2,2])
print(a)
# print(a[:,0])

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [4]:
sess = tf.InteractiveSession()
b = tf.square(a)
print(b.eval())
b = tf.cast(b,dtype=tf.float32)
e = tf.sqrt(b)
print(e.eval())

[[[[  0   1]
   [  4   9]]

  [[ 16  25]
   [ 36  49]]]


 [[[ 64  81]
   [100 121]]

  [[144 169]
   [196 225]]]]
[[[[  0.           0.99999994]
   [  1.99999988   2.99999976]]

  [[  3.99999976   5.        ]
   [  5.99999952   6.99999952]]]


 [[[  7.99999952   8.99999905]
   [ 10.          10.99999905]]

  [[ 11.99999905  12.99999905]
   [ 13.99999905  14.99999905]]]]


In [7]:
a = tf.convert_to_tensor(a)
print(a.get_shape())
a = tf.reduce_sum(a,-2,keep_dims = True)
print(a.eval())
print(a.get_shape())

(2, 2, 2, 2)
[[[[ 2  4]]

  [[10 12]]]


 [[[18 20]]

  [[26 28]]]]
(2, 2, 1, 2)


In [14]:
# tf.tile
import tensorflow as tf
temp = tf.tile([[1,2,3],[1,2,3]],[1,1])
temp2 = tf.tile([[1,2,3],[1,2,3]],[2,1])
temp3 = tf.tile([[1,2,3],[1,2,3]],[2,2])
with tf.Session() as sess:
    print(sess.run(temp))
    print(sess.run(temp2))
    print(sess.run(temp3))

[[1 2 3]
 [1 2 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]
 [1 2 3 1 2 3]]


In [5]:
x = np.ones([10,16,1])
y = tf.nn.softmax(x)
sess = tf.InteractiveSession()
print(y.get_shape())

(10, 16, 1)


In [7]:
x1 = np.ones([2,3])
x2 = np.ones([2,3])
x3 = tf.multiply(x1,x2)
print(x3.get_shape())

(2, 3)
